# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 532aa07aa5c640cced32274a966423be3bc34315be551314ab3d5bc638f4a040a0f4a3f5f3e3d54cff8d855c78179b74f9193d55f3380469cef54286db4ba57e
  username: username
  password: password
  instagram_access_token: <%= ENV["INSTAGRAM_ACCESS_TOKEN"] %>

test:
  secret_key_base: a7c3a64607db1e49b7dc2dc8d4abd222242d513c9302f26ed100db80204b65bf65432e81c93f1b721df02f1dba6b2059e2380420304f89192d9beba725ba1641
  username: username
  password: password
  instagram_access_token: <%= ENV["INSTAGRAM_ACCESS_TOKEN"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  username: <%= ENV["AUTH_USERNAME"] %>
  password: <%= ENV["AUTH_PASSWORD"] %>
  instagram_access_token: <%= ENV["INSTAGRAM_ACCESS_TOKEN"] %>